//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_programciligi_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevaplar
    {
        public int cevap_id { get; set; }
        public string cevap { get; set; }
        public int uye_id { get; set; }
        public int soru_id { get; set; }
    
        public virtual sorular sorular { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
