//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_programciligi_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sorular()
        {
            this.cevaplar = new HashSet<cevaplar>();
        }
    
        public int soru_id { get; set; }
        public string soru { get; set; }
        public int uye_id { get; set; }
        public int kategori_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cevaplar> cevaplar { get; set; }
        public virtual kategoriler kategoriler { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
