//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internet_programciligi_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.cevaplar = new HashSet<cevaplar>();
            this.sorular = new HashSet<sorular>();
        }
    
        public int uye_id { get; set; }
        public string uye_ad_soyad { get; set; }
        public string uye_mail { get; set; }
        public string uye_cinsiyet { get; set; }
        public string uye_dogum_tarihi { get; set; }
        public string uye_kullanici_adi { get; set; }
        public string uye_parola { get; set; }
        public int uye_yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cevaplar> cevaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sorular> sorular { get; set; }
    }
}
